- hosts: all
  tasks:

  - name: get public IP
    ipify_facts:
    register: public_ip

  - name: Print host info
    vars:
      info: |
           Hostname = {{ ansible_hostname }}
           OS = {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_machine }})
           IP = {{ ansible_all_ipv4_addresses }}
           User: {{ ansible_user_id }} {{ ansible_user_gecos }}
           Directory = {{ playbook_dir }}
           VirtualizationType = {{ ansible_virtualization_type }}
           Public IP = {{ ipify_public_ip }}
    debug:
      msg: "{{ info.split('\n') }}"

#  - name: Display all variables/facts known for a host
#    debug:
#      var: hostvars[inventory_hostname]
