- hosts: localhost
  tasks:

  - name: Check host
    command: cat /etc/hostname
    
  - name: NTP Install
    become: true
    yum:
      name: ntp
      state: present

  - name: NTP Enable and start service
    become: true
    service:
      enabled: yes
      name: ntpd
      state: started
