- hosts: localhost 10.1.3.43
  tasks:

  - name: Check host
    shell: cat /etc/hostname && whoami && pwd && ip address
    register: myhost
  - debug: msg="{{myhost.stdout}}"
  
  - name: EPEL repo - Install.
    become: true
    package:
       name={{item}} 
       state=present
    with_items:
      - epel-release
    register: epel_installed

  - name: Basic tools - Install.
    become: true
    package:
       name={{item}}
       state=present
    with_items:
      - vim
      - nano
      - mc
      - wget
      - htop
    when: epel_installed|succeeded

