- hosts: localhost
  tasks:


  - name: EPEL repo - Install.
    become: true
    package:
       name={{item}} 
       state=present
    with_items:
      - epel-release
    register: epel_installed

  - name: Basic tools - Install.
    become: true
    package:
       name={{item}}
       state=present
    with_items:
      - vim
      - nano
      - mc
      - wget
      - htop
    when: epel_installed|succeeded

