- hosts: localhost
  tasks:

  - name: NTP Install
    become: true
    yum:
      name: ntp
      state: present
    register: ntp_installed

  - name: NTP Enable and start service
    become: true
    service:
      enabled: yes
      name: ntpd
      state: started
    when: ntp_installed|succeeded
